### ISSUE TITLE
Training command.

### ISSUE THREAD

**Issue by weimengchuan** [Sranc3/M-BEV#5]
Hi, thanks for the great work!

I wonder how do you train the model. Can you provide the training command?

Thanks in advance!

**Comment by Sranc3** [comment]
The training command is:
tools/dist_train.sh projects/configs/petrv2/petrv2_vovnet_gridmask_mbev_p4_800x320.py 8 --work-dir work_dirs/your path
Remember to modify your config file, and by default is training is with one random missed camera.
